name: meai_assistant
description: A Flutter plugin for embedding a customizable AI assistant in your app. Allows easy customization of assistant name, logos, colors, and text.
version: 1.0.0
homepage: https://github.com/yourusername/meai_assistant
repository: https://github.com/yourusername/meai_assistant
issue_tracker: https://github.com/yourusername/meai_assistant/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  provider: ^6.1.2
  flutter_mobx: ^2.3.0
  mobx: ^2.5.0
  lottie: ^3.3.0
  flutter_keyboard_visibility: ^6.0.0
  animate_do: ^4.2.0
  shimmer: ^3.0.0
  crypto: ^3.0.5
  package_info_plus: ^8.0.0
  keystore_signature: ^1.0.0
  ios_teamid: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  mobx_codegen: ^2.7.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/lottie/
  
  fonts:
    - family: ReadexPro
      fonts:
        - asset: assets/fonts/readexpro/ReadexPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/readexpro/ReadexPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/readexpro/ReadexPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/readexpro/ReadexPro-Light.ttf
          weight: 300
        - asset: assets/fonts/readexpro/ReadexPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/readexpro/ReadexPro-ExtraLight.ttf
          weight: 200

